### ISSUE TITLE
Audio not working on Steam Deck

### ISSUE THREAD

**Issue by DocMAX** [LukeShortCloud/steamos-linux-neptune#1]
Is audio supposed to work on steam deck? On mine it's not working. I have a device called "ACP/ACP3X/ACP6x Audio Coprocessor" but Stereo-Output is "disconnected".

**Comment by RustyRaptor** [comment]
Does it work when you plug in headphones? In my case it works when I plug in headphones but the speakers do not work. I wonder if there needs to be some other software that switches it to speaker mode. I know steamos has some weird setup going on with audio.

**Comment by LukeShortCloud** [comment]
@DocMAX @RustyRaptor For full audio support, you'll need to use (1) the SteamOS kernel or the upstream Linux kernel 6.1 or newer and (2) install the acp5x-ucm-files audio configuration.

https://linuxgamingcentral.com/posts/audio-on-deck-support-outside-of-steamos/
https://gitlab.com/open-sd/acp5x-ucm-files

Apologies for the delayed response. I do not monitor this repository and should have disabled GitHub issues on here. I'm not a maintainer of the kernel itself. This repository for the kernel is a mirror of Valve's source code.

winesapOS is my project I actively maintain and monitor. I take SteamOS source code and build and ship it with the latest Arch Linux packages.

https://github.com/LukeShortCloud/winesapOS

**Comment by DocMAX** [comment]
ALSA UCM has been uptated. So one just needs Kernel 6.1...

**Comment by LukeShortCloud** [comment]
Yes, it appears to have been merged in about a month and a half ago. Good to know!

https://github.com/alsa-project/alsa-ucm-conf/commit/6dd80aee34dbff85de5818b9181bb382dfe868ec

If you happen to have any other issues, let me know and i can try to help!
